# Generated by Django 5.2.14 on 2026-05-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='campuses.campus'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_campus_pastor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_group_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_volunteer_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
